project:
  type: website

website:
  title: "TODO"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: pulse
    css: styles.css
    toc: true

editor: visual

body-footer: |
  The TODO project is a project of the Election Law Clinic at Harvard Law School.
  Election data is originally from the [Voting and Election Science Team](https://dataverse.harvard.edu/dataverse/electionscience).
  Joined demographic and election data is used from ALARM Project's [2020 Redistricting Data Files](https://alarm-redist.github.io/posts/2021-08-10-census-2020/).
  TODO disclaimer.
