project:
  type: website

website:
  title: "RPV Near Me"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - data.qmd
  page-footer:
    center: |
      RPV Near Me is a project of the [Election Law Clinic (ELC) at Harvard Law School](https://www.hlselectionlaw.org/). <br>
      The mission of the ELC is to train the next generation of election lawyers through litigation and advocacy that bring novel academic ideas to the practice of election law. We aim to build power for voters, not politicians.<br>
      Election data is originally from the [Voting and Election Science Team](https://dataverse.harvard.edu/dataverse/electionscience).
      Joined demographic and election data is used from ALARM Project's [2020 Redistricting Data Files](https://alarm-redist.github.io/posts/2021-08-10-census-2020/).
    border: true
    background: light

format:
  html:
    theme: pulse
    css: styles.css
    toc: true

editor: visual

