---
title: "NY"
description: |
  Ecological inference estimates by county for NY
format: html
server: shiny
---

```{r}
#| echo: false
#| message: false
library(tidyverse)
library(ggiraph)
library(ggdist)
alarm_abb <- function() {
  tibble::tribble(
    ~a, ~b,
    'pre', 'President',
    'uss', 'US Senate',
    'gov', 'Governor',
    'atg', 'Attorney General',
    'sos', 'Secretary of State'
  )
}


counties <- tinytiger::tt_counties('NY')
p <- counties |> 
  ggplot() +
  geom_sf_interactive(aes(fill = 'white', color = 'black')) +
  geom_sf_text(aes(label = NAME), fun.geometry = \(x) geomander::st_circle_center(sf::st_as_sf(x))) +
  theme_void() +
  guides(fill = 'none') +
  theme(text = element_text(family = 'Arial', size = 1))
ei_tb <- readRDS('~/GitHub/US-ei/data-out/NY_2020/NY_county_2020_ei.rds')
ei_tb <- bind_rows(lapply(ei_tb, bind_rows), .id = 'county')
  
ei_tb <- ei_tb  |> 
  mutate(
    race = recode(
      race,
      'vap_black' = 'Black',
      'vap_hisp' = 'Hispanic',
      'vap_oth' = 'Other',
      'vap_white' = 'White'
    ),
    race = factor(race, levels = c('White', 'Black', 'Hispanic', 'Other'))
  ) |>
  filter(str_detect(cand, '_dem')) |>
  mutate(election = word(cand, sep = fixed('_')),
         election = recode(election, !!!deframe(alarm_abb())),
         year = 2000 + as.integer(str_sub(cand, 5, 6)),
         election = paste(election, year)) |>
  arrange(year, election) |>
  mutate(election = fct_inorder(election))
```

```{r}
girafeOutput('map')
plotOutput('ei')
```

```{r}
#| context: server
output$map <- renderGirafe({
    girafe(ggobj = p)
  })
output$ei <- renderPlot({
  ei_tb |>
    filter(county == map_selected) |>
    ggplot() +
    geom_interval(aes(y = election, x = mean, xmin = ci_95_lower, xmax = ci_95_upper, color = race),
                  position = position_dodge(width = .5)) +
    geom_pointinterval(aes(y = election, x = mean, xmin = mean, xmax = mean, group = race),
                       position = position_dodge(width = .5), color = 'black') +
    scale_x_continuous(name = 'Estimated Support for Democrats', labels = scales::percent, limits = c(0, 1)) +
    scale_y_discrete(name = 'Contest', limits = rev) +
    theme_bw()
})
```
